version: '3'
services:
  fdlb_backend:
    container_name: backend
    env_file: ./envs/local.env
    build:
      context: ./fdlb_backend/
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:7000"
    volumes:
      - ./fdlb_backend:/fdlb_backend
    ports:
      - "7000:7000"
