version: '3'
services:
  fdlb_backend:
    container_name: backend
    env_file: ./envs/local.env
    build:
      context: ./fdlb_backend/
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:7000"
    volumes:
      - './fdlb_backend:/backend_fdlb'
    ports:
      - "7000:7000"

  fdlb_front:
    container_name: fdlb_front
    build:
      context: ./fdlb_front
      dockerfile: Dockerfile
    volumes:
      - './fdlb_front:/usr/src/app'
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development

  postgres:
    container_name: fdlb_postgres
    image: postgres:10.2
    env_file: ./envs/local.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres: