# Generated by Django 2.0 on 2018-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
