# Generated by Django 2.0 on 2018-03-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='mimetype',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
