# Generated by Django 2.0 on 2018-03-29 16:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180329_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/user_content/img/'), upload_to=''),
        ),
    ]
