# Generated by Django 2.0 on 2018-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('shape', models.BinaryField()),
                ('body', models.BinaryField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
