# Generated by Django 2.0 on 2018-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_neural_network', '0002_auto_20180321_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmodel',
            name='lambda_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='weightmodel',
            name='learn_rate',
            field=models.FloatField(default=-1),
        ),
    ]
